[project]
name = 'QIMAAH'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.multiversal-artwork]
path = 'contracts/multiversal-artwork.clar'
clarity_version = 2
epoch = 2.5

[contracts.multiversal-auction]
path = 'contracts/multiversal-auction.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-rng]
path = 'contracts/quantum-rng.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
